create table user (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(255),
	password VARCHAR(255) NOT NULL
);

create table customer (
	name VARCHAR(255) NOT NULL,
	user_id INTEGER
);

create table account (
	number VARCHAR(255) PRIMARY KEY,
	description VARCHAR(255) NOT NULL,
	balance BIGINT NOT NULL,
  	max_balance BIGINT NOT NULL,
  	version INTEGER
);

create table customer_account (
	customer_id INTEGER,
	number VARCHAR(255),
	PRIMARY KEY(customer_id, number) 
);

create table account_transaction (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	from_account_number VARCHAR(255),
	to_account_number VARCHAR(255),
	amount  BIGINT NOT NULL,
	time datetime NOT NULL
);

